### ISSUE TITLE
翻訳者の追加

### ISSUE THREAD

**Issue by minorua** [OSGeo-jp/QGIS#24]
QGIS 3.0のリリースはまだかまだかと思っております。いつリリースされるのかわかりませんが、GUI翻訳の進捗は何と100%を達成しています。Transifex APIで見たところKohei Tomita (fairtommy)さんが多くの翻訳をして下さっています。感謝の気持ちを込めてTomitaさんを3.0のリリース前に翻訳者一覧に追加しませんか? 嘉山さん(@yoichigmf )、ご検討をよろしくお願いします。

集計用スクリプト: https://gist.github.com/minorua/fe1ff7c04d13ada48ade8a2e2892d156

**Comment by yoichigmf** [comment]
追加に賛成します

**Comment by minorua** [comment]
昨日プルリクエストを行いました(qgis/QGIS#6352)。Tomitaさん、ありがとうございました。
